### ISSUE TITLE
加载模块失败

### ISSUE THREAD

**Issue by Yihy** [1615450788/vue-cron#5]
你好,我使用[electron-vue](https://github.com/SimulatedGREG/electron-vue)脚手架构建项目,添加到package.json后,安装,在vue里面引入你的模块.运行后,提示我Cannot find module 'vue-cron'

**Comment by 1615450788** [comment]
请确认是否已引入模块 npm install vue-cron

**Comment by Yihy** [comment]
确定引入了

**Comment by Yihy** [comment]
引入了源码,搞定了.
我是勉强能用node的东西,自己私下拿来玩的.我猜测原因可能是引入模块后,webpack再次进行打包,导致找不到模块.
直接引入编译后的js,会报 `Cannot assign to read only property 'exports' of object '#<Object>'`[解决办法](https://blog.csdn.net/u013034736/article/details/70174425)
不过不喜欢这种方式,我选择引入你的源码编译.
对功能上提供个建议:希望增加cron反解析到ui和最近几次运行时间显示.

**Comment by Yihy** [comment]
我的是在浏览器控制台上报 找不到vue-cron模块

**Comment by 1615450788** [comment]
@PiedPiperr  之前有考虑过将周单独抽离出来，但是发现周跟天的逻辑是有一定关联性的，而且目前已有的一些在线cron表达式生成器都没有单独出周来配置，所以我也就照旧了！

**Comment by 1615450788** [comment]
@Yihy 之前是有考虑过源码引入的，但是由于目前大家使用构建工具都是习惯性不编译node_modules的，所以我使用了预发布压缩包的方式提供默认依赖，当然，如果你想实时修改或者调试完全可以依赖源码，至于你说的cron.min.js引入会报错的问题我会去检查一下

**Comment by 1615450788** [comment]
@Yihy 还有，你说的表达式的解析及反解析的问题，是我下个版本的计划，当然，如果可以的话也欢迎你的贡献:blush:

**Comment by Yihy** [comment]
@1615450788 我简单看过源码.有空的时候,我去尝试修改修改.

**Comment by 1615450788** [comment]
已于`v1.0.7`版本中修复
