### ISSUE TITLE
cron问题

### ISSUE THREAD

**Issue by PiedPiperr** [1615450788/vue-cron#8]
选择每隔1分钟执行，从第1分钟开始的cron:  * 1/1 * * * ? * 是错误的，
正确的应该是  0 1/1 * * * ? *
" 星号"代表每一个这样的时间节点都执行。在这控件中，如果单独选择‘天’，秒分时都是"星号"，意味着还是每秒都执行

**Comment by 1615450788** [comment]
没有对更小粒度的时间进行设0操作，是考虑到从秒开始设置到年的过程中会覆盖掉之前的设置，所以才去了这种分而治之的方式，不处理相互的主观关联关系！

**Comment by PiedPiperr** [comment]
@1615450788  
其实目前这样子确实是最合理的。另外考虑到实际用户去组件里选时间，就有点不好搞了，他们可能只会从字面理解上去选。
前段时间，我擅自将您代码拷贝下来做了些修改：限制用户从小时间往大时间去选择。但是感觉这样有点反人类zzz
